[package]
name = "localization"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true
build = "build.rs"

[lints]
workspace = true

[dependencies]
gettext-rs.workspace = true
