# Do not edit this file.
# To change Linux package dependencies, edit `NIX_PACKAGES` in
# `crates/xtask/src/linux_packaging.rs`, then run `just deps`.
{
  description = "Native GTK4/libadwaita music player for Jellyfin, Subsonic, Navidrome and local libraries written in Rust";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs =
    { self, nixpkgs }:
    let
      systems = [
        "x86_64-linux"
        "aarch64-linux"
      ];
      forAllSystems = nixpkgs.lib.genAttrs systems;
    in
    {
      packages = forAllSystems (
        system:
        let
          pkgs = import nixpkgs { inherit system; };
          inherit (pkgs) lib;
          workspaceManifest = builtins.fromTOML (builtins.readFile ./Cargo.toml);
        in
        rec {
          rufin = pkgs.rustPlatform.buildRustPackage {
            pname = "rufin";
            version = workspaceManifest.workspace.package.version;

            src = lib.fileset.toSource {
              root = ./.;
              fileset = lib.fileset.unions [
                ./Cargo.lock
                ./Cargo.toml
                ./CMakeLists.txt
                ./LICENSE
                ./README.md
                ./cmake
                ./crates
                ./data/icons/hicolor
                ./data/icons/rufin-icons.gresource.xml
                ./data/japanese-readings.dic
                ./data/japanese-readings.LICENSE
                ./data/io.github.screwys.Rufin.desktop
                ./data/io.github.screwys.Rufin.metainfo.xml
                ./locales
              ];
            };

            cargoLock = {
              lockFile = ./Cargo.lock;
            };

            strictDeps = true;

            nativeBuildInputs = with pkgs; [
              cmake
              gettext
              ninja
              pkg-config
              wrapGAppsHook4
            ];

            # Generated Linux package dependencies start.
            buildInputs =
              with pkgs;
              [
                glib
                gtk4
                libadwaita
                glib-networking
              ]
              ++ (with gst_all_1; [
                gstreamer
                gst-plugins-base
                gst-plugins-good
                gst-plugins-bad
                gst-plugins-ugly
                gst-libav
              ]);
            # Generated Linux package dependencies end.

            doCheck = false;

            SSL_CERT_FILE = "${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt";

            buildPhase = ''
              runHook preBuild

              cmake \
                -S . \
                -B build-cmake \
                -G Ninja \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX="$out" \
                -DRUFIN_BUILD_IDENTITY=stable \
                -DRUFIN_CARGO_FROZEN=ON
              cmake --build build-cmake --target rufin

              runHook postBuild
            '';

            installPhase = ''
              runHook preInstall

              cmake --install build-cmake
              substituteInPlace "$out/share/applications/io.github.screwys.Rufin.desktop" \
                --replace-fail "Exec=rufin" "Exec=$out/bin/rufin"

              runHook postInstall
            '';

            preFixup = ''
              gappsWrapperArgs+=(
                --set-default RUFIN_LOCALEDIR "$out/share/locale"
                --set-default SSL_CERT_FILE "${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt"
              )
            '';

            meta = {
              description = "Native GTK4/libadwaita music player for Jellyfin, Subsonic, Navidrome and local libraries written in Rust";
              homepage = "https://github.com/screwys/Rufin";
              license = lib.licenses.gpl3Plus;
              mainProgram = "rufin";
              platforms = lib.platforms.linux;
            };
          };

          default = rufin;
        }
      );

      apps = forAllSystems (system: {
        default = {
          type = "app";
          program = "${self.packages.${system}.default}/bin/rufin";
          meta.description = self.packages.${system}.default.meta.description;
        };
      });

      checks = forAllSystems (system: {
        default = self.packages.${system}.default;
      });

      devShells = forAllSystems (
        system:
        let
          pkgs = import nixpkgs { inherit system; };
          defaultShell = pkgs.mkShell {
            packages =
              with pkgs;
              [
                ast-grep
                cargo
                cargo-deny
                cargo-nextest
                clippy
                cmake
                debugedit
                desktop-file-utils
                fakeroot
                file
                gettext
                git
                just
                jq
                libarchive
                ninja
                pacman
                pkg-config
                rustc
                rustfmt
                wavpack
                zstd
              ]
              # Generated Linux development dependencies start.
              ++ (with pkgs; [
                glib
                gtk4
                libadwaita
                glib-networking
              ])
              ++ (with pkgs.gst_all_1; [
                gstreamer
                gst-plugins-base
                gst-plugins-good
                gst-plugins-bad
                gst-plugins-ugly
                gst-libav
              ]);
            # Generated Linux development dependencies end.

            GIO_EXTRA_MODULES = "${pkgs.glib-networking}/lib/gio/modules";
            RUFIN_LOCALEDIR = "locales";
          };
        in
        {
          default = defaultShell;
          packaging = pkgs.mkShell {
            inputsFrom = [ defaultShell ];
            packages = with pkgs; [
              bubblewrap
              dbus
              docker-client
              flatpak
              flatpak-builder
            ];
            RUFIN_LOCALEDIR = "locales";
          };
        }
      );

      formatter = forAllSystems (system: nixpkgs.legacyPackages.${system}.nixfmt);
    };
}
