[package]
name = "sources"
autotests = false
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
async-channel.workspace = true
base64.workspace = true
blake3.workspace = true
futures-util.workspace = true
getrandom.workspace = true
gstreamer-pbutils = { workspace = true, features = ["v1_26"] }
if-addrs.workspace = true
library.workspace = true
lofty.workspace = true
md5.workspace = true
notify.workspace = true
playback.workspace = true
reqwest = { workspace = true, features = ["json"] }
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_path_to_error.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-tungstenite.workspace = true
tracing.workspace = true
url.workspace = true
walkdir.workspace = true

[dev-dependencies]
tokio-rustls.workspace = true
wiremock.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
winsafe.workspace = true

[lints]
workspace = true
