[package]
name = "ui-library"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
sources.workspace = true
downloads.workspace = true

tracing.workspace = true
ui-shared.workspace = true
rufin-core.workspace = true
library.workspace = true
playback.workspace = true
artwork.workspace = true
localization.workspace = true
gtk = { workspace = true, features = ["v4_20"] }
adw = { workspace = true, features = ["v1_9", "gtk_v4_20"] }
tokio.workspace = true


[lints]
workspace = true

[build-dependencies]
glib-build-tools.workspace = true
