name: Feature request
description: Suggest a new feature or improvement for Rufin.
title: "[Feature]: "
body:
  - type: checkboxes
    id: duplicate-check
    attributes:
      label: Duplicate check
      options:
        - label: I have already searched through open/closed issues
          required: true

  - type: dropdown
    id: source
    attributes:
      label: Source
      options:
        - Local
        - Jellyfin
        - Navidrome
        - OpenSubsonic
        - Emby
        - Plex
        - WebDAV
        - Samba
        - Unrelated
    validations:
      required: true

  - type: textarea
    id: feature
    attributes:
      label: Please describe the feature
      description: Explain the requested behavior and what a good implementation should be like. Is this implemented in other apps?
    validations:
      required: true
