[package]
name = "secrets"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
app-identity.workspace = true
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[target.'cfg(all(unix, not(any(target_os = "android", target_vendor = "apple"))))'.dependencies]
oo7.workspace = true
tokio = { workspace = true, features = ["rt", "time"] }

[target.'cfg(target_os = "windows")'.dependencies]
keyring-core.workspace = true
windows-native-keyring-store.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
apple-native-keyring-store.workspace = true
keyring-core.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
