[package]
name = "playback-gstreamer"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
audio-processing.workspace = true
gstreamer = { workspace = true, features = ["v1_26"] }
gstreamer-audio = { workspace = true, features = ["v1_26"] }
playback.workspace = true
tracing.workspace = true

[dev-dependencies]
library.workspace = true
gstreamer-app = { workspace = true, features = ["v1_26"] }
tempfile.workspace = true

[lints]
workspace = true
