[package]
name = "rufin"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true
keywords = ["jellyfin", "emby", "plex", "navidrome", "subsonic"]
categories = ["multimedia::audio", "gui"]
build = "build.rs"

[features]
development = ["app-identity/development"]

[[bin]]
name = "rufin"
path = "src/main.rs"

[dependencies]
rufin-core.workspace = true
app-identity.workspace = true
desktop-integration.workspace = true
localization.workspace = true
playback.workspace = true
playback-gstreamer.workspace = true
sources.workspace = true
tracing.workspace = true
ui-shell.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows-updater.workspace = true

[lints]
workspace = true
