mod album_detail;
mod album_detail_view;
mod artist;
mod artist_releases;
pub(super) mod cards;
pub(crate) mod collection_context;
pub(crate) mod collections;
mod columns;
pub(crate) mod detail_links;
mod detail_showcase;
pub(crate) mod folders;
pub(crate) mod grid_cells;
mod grouped_detail;
pub(crate) mod home;
mod home_layout;
mod interchange;
pub(crate) mod library_fields;
pub(crate) mod named_collections;
mod named_detail;
pub(crate) mod playlist_detail;
mod playlist_entries;
mod playlist_entry_model;
pub(crate) mod playlist_picker;
mod recycled_cells;
pub(crate) use recycled_cells::{RecycledArtworkCell, RecycledTextCell};
pub(super) mod release_kind;
pub(crate) mod route;
pub(crate) mod route_layout;
mod route_shell;
mod routes;
mod search;
pub(crate) mod sparse_model;
mod table_links;
mod table_sizing;
mod track_model;
pub(crate) mod track_selection;

pub(crate) use album_detail::{AlbumCollectionOrder, album_detail_rows_for_items};
pub(crate) use artist::{
    artist_detail_route, load_artist_discography, load_artist_overview, load_artist_tracks,
};
pub(crate) use named_detail::{NamedDetailId, load_named_detail};
pub(crate) use playlist_detail::load_smart_playlist_detail;
