if(DEFINED ENV{CARGO_TARGET_DIR} AND NOT "$ENV{CARGO_TARGET_DIR}" STREQUAL "")
  set(RUFIN_CARGO_TARGET_DIR "$ENV{CARGO_TARGET_DIR}")
else()
  set(RUFIN_CARGO_TARGET_DIR "${CMAKE_CURRENT_SOURCE_DIR}/target")
endif()
cmake_path(ABSOLUTE_PATH RUFIN_CARGO_TARGET_DIR
  BASE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
  NORMALIZE)

set(RUFIN_CARGO_ARGUMENTS build)
if(RUFIN_CARGO_FROZEN)
  list(APPEND RUFIN_CARGO_ARGUMENTS --frozen)
else()
  list(APPEND RUFIN_CARGO_ARGUMENTS --locked)
endif()
list(APPEND RUFIN_CARGO_ARGUMENTS --package rufin)

if(NOT RUFIN_CARGO_PROFILE STREQUAL "auto")
  set(RUFIN_RESOLVED_CARGO_PROFILE "${RUFIN_CARGO_PROFILE}")
elseif(CMAKE_BUILD_TYPE MATCHES "^(Release|RelWithDebInfo|MinSizeRel)$")
  set(RUFIN_RESOLVED_CARGO_PROFILE release)
else()
  set(RUFIN_RESOLVED_CARGO_PROFILE debug)
endif()

if(RUFIN_RESOLVED_CARGO_PROFILE STREQUAL "release")
  list(APPEND RUFIN_CARGO_ARGUMENTS --release)
elseif(NOT RUFIN_RESOLVED_CARGO_PROFILE STREQUAL "debug")
  list(APPEND RUFIN_CARGO_ARGUMENTS --profile "${RUFIN_RESOLVED_CARGO_PROFILE}")
endif()
if(RUFIN_BUILD_IDENTITY STREQUAL "development")
  list(APPEND RUFIN_CARGO_ARGUMENTS --features development)
endif()

set(RUFIN_CARGO_EXECUTABLE
  "${RUFIN_CARGO_TARGET_DIR}/${RUFIN_RESOLVED_CARGO_PROFILE}/rufin${CMAKE_EXECUTABLE_SUFFIX}")
set(RUFIN_CMAKE_EXECUTABLE
  "${CMAKE_CURRENT_BINARY_DIR}/bin/rufin${CMAKE_EXECUTABLE_SUFFIX}")
set(RUFIN_CARGO_ENVIRONMENT
  "CARGO_TARGET_DIR=${RUFIN_CARGO_TARGET_DIR}"
  "CMAKE_GENERATOR=${CMAKE_GENERATOR}"
)
if(APPLE)
  list(APPEND RUFIN_CARGO_ENVIRONMENT
    "MACOSX_DEPLOYMENT_TARGET=${RUFIN_MACOS_DEPLOYMENT_TARGET}")
endif()

add_custom_target(rufin ALL
  COMMAND "${CMAKE_COMMAND}" -E make_directory "${CMAKE_CURRENT_BINARY_DIR}/bin"
  COMMAND "${CMAKE_COMMAND}" -E env
    ${RUFIN_CARGO_ENVIRONMENT}
    "${RUFIN_CARGO}" ${RUFIN_CARGO_ARGUMENTS}
  COMMAND "${CMAKE_COMMAND}" -E copy_if_different
    "${RUFIN_CARGO_EXECUTABLE}" "${RUFIN_CMAKE_EXECUTABLE}"
  BYPRODUCTS "${RUFIN_CMAKE_EXECUTABLE}"
  WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
  USES_TERMINAL
  COMMAND_EXPAND_LISTS
  VERBATIM
)
