[package]
name = "rufin-provider-subsonic"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = "0.1.89"
getrandom = "0.4.0"
md5 = "0.8.0"
reqwest = { version = "0.13.3", features = ["json"] }
rufin-core = { path = "../rufin-core" }
rufin-provider = { path = "../rufin-provider" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tracing = "0.1.41"

[dev-dependencies]
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
wiremock = "0.6.5"

[lints]
workspace = true
